import sys, os
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')
sys.path.insert(0, r'C:\QuantLab\Data_Lab')
sys.path.insert(0, r'C:\QuantLab\Data_Lab\shared')
sys.path.insert(0, r'C:\QuantLab\Data_Lab\shared\config')
sys.path.insert(0, r'C:\QuantLab\Data_Lab\tools')

from datetime import datetime
from pathlib import Path
import subprocess


ROOT = Path(r"C:\QuantLab\Data_Lab")
OUTPUT_DIR = ROOT / "scratch" / "dashboard_hub"
OUTPUT_FILE = OUTPUT_DIR / "index.html"

def _news_flow_output() -> Path:
    """Return today's News Flow HTML path."""
    from datetime import date
    return ROOT / "News_flow" / f"{date.today().isoformat()}.html"


DASHBOARDS = [
    {
        "title": "Dashboard Hub",
        "category": "Launcher",
        "script": None,
        "output": OUTPUT_FILE,
        "description": "Central landing page for all live QuantLab dashboards.",
    },
    {
        "title": "War Room News Flow",
        "category": "Pre-Market",
        "script": None,  # generated by scan_news.py on schedule; hub links to today's file
        "output": _news_flow_output(),
        "description": "Pre-market catalyst feed — Alpaca ticker news + Tavily sector sweeps. Runs at 6:30 / 7:30 / 8:06 AM CT Mon–Fri.",
    },
    {
        "title": "QuantLab Morning Dashboard",
        "category": "Macro",
        "script": ROOT / "scratch" / "dashboard" / "morning_dashboard.py",
        "output": ROOT / "scratch" / "dashboard" / "index.html",
        "description": "Primary macro war room dashboard with regime, liquidity, baskets, and tactical context.",
    },
    {
        "title": "Diet CTA Dashboard",
        "category": "Macro",
        "script": ROOT / "scratch" / "dashboard_cta" / "run_diet_cta.py",
        "output": ROOT / "scratch" / "dashboard_cta" / "index.html",
        "description": "Systematic positioning proxy using COT, XLY/XLP, HY spreads, and the yield curve.",
    },
    {
        "title": "PM + Crypto Dashboard",
        "category": "Quant",
        "script": ROOT / "scratch" / "pm_crypto_dashboard" / "pm_crypto_dashboard.py",
        "output": ROOT / "scratch" / "pm_crypto_dashboard" / "index.html",
        "description": "Prediction-market and crypto cross-asset dashboard tracking macro odds and sentiment.",
    },
    {
        "title": "Theme Signal Intelligence",
        "category": "Quant",
        "script": ROOT / "studies" / "theme_signals_dashboard" / "theme_dashboard.py",
        "output": ROOT / "studies" / "theme_signals_dashboard" / "outputs" / "index.html",
        "description": "Theme dashboard for Space Economy and AI demand-cycle confirmation.",
    },
    {
        "title": "Macro Dashboard Legacy",
        "category": "Macro",
        "script": ROOT / "scratch" / "Macro_dashboard" / "morning_dashboard.py",
        "output": ROOT / "scratch" / "Macro_dashboard" / "index.html",
        "description": "Legacy macro dashboard retained for comparison and alternate layout reference.",
    },
]


def run_dashboard(script_path: Path | None, expected_output: Path) -> tuple[bool, str]:
    if script_path is None:
        return True, "Hub page generated"
    env = os.environ.copy()
    env["QUANTLAB_NO_OPEN"] = "1"
    env["PYTHONIOENCODING"] = "utf-8"
    proc = subprocess.run(
        [sys.executable, str(script_path)],
        cwd=str(ROOT),
        env=env,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        timeout=180,
    )
    output = (proc.stdout or "") + (proc.stderr or "")
    lines = [line.strip() for line in output.strip().splitlines() if line.strip()] if output.strip() else []
    if proc.returncode == 0:
        preferred = [
            line for line in lines
            if any(token in line.lower() for token in ["diet cta score", "signal summary"])
        ]
        filtered = [
            line for line in preferred
            if not any(token in line.lower() for token in ["failed download", "futurewarning", "warning:"])
        ]
        chosen = filtered[-2:] if filtered else []
        prefix = f"Refreshed successfully: {expected_output.relative_to(ROOT).as_posix()}"
        message = f"{prefix} | {' | '.join(chosen)}" if chosen else prefix
    else:
        tail = lines[-3:] if lines else []
        message = " | ".join(tail) if tail else "No output"
    return proc.returncode == 0, message


def file_href(path: Path) -> str:
    return path.as_uri()


def render_hub(results: list[dict]) -> None:
    timestamp = datetime.now().strftime("%Y-%m-%d %I:%M %p CT")
    cards = []
    for item in results:
        status_color = "#26a69a" if item["ok"] else "#ef5350"
        status_label = "UPDATED" if item["ok"] else "FAILED"
        output_exists = item["output"].exists()
        modified = datetime.fromtimestamp(item["output"].stat().st_mtime).strftime("%Y-%m-%d %I:%M %p") if output_exists else "Missing"
        open_link = f'<a class="button" href="{file_href(item["output"])}">Open Dashboard</a>' if output_exists else '<span class="button disabled">No Output</span>'
        script_text = item["script"].relative_to(ROOT).as_posix() if item["script"] else "Generated by hub updater"
        output_text = item["output"].relative_to(ROOT).as_posix()
        cards.append(f"""
        <div class="card">
          <div class="card-head">
            <div>
              <div class="kicker">{item['category']}</div>
              <h2>{item['title']}</h2>
            </div>
            <div class="status" style="border-color:{status_color};color:{status_color};">{status_label}</div>
          </div>
          <p>{item['description']}</p>
          <div class="meta"><span>Script</span><strong>{script_text}</strong></div>
          <div class="meta"><span>Output</span><strong>{output_text}</strong></div>
          <div class="meta"><span>Last Modified</span><strong>{modified}</strong></div>
          <div class="runlog">{item['message']}</div>
          <div class="actions">{open_link}</div>
        </div>
        """)

    html = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>QuantLab Dashboard Hub</title>
      <style>
        body {{ margin: 0; background: radial-gradient(circle at top, #162236 0%, #0d1117 46%, #080b10 100%); color: #e6edf3; font-family: Segoe UI, Arial, sans-serif; }}
        .wrap {{ max-width: 1440px; margin: 0 auto; padding: 28px 24px 40px; }}
        .hero {{ margin-bottom: 22px; }}
        .hero h1 {{ margin: 0; font-size: 36px; }}
        .hero p {{ margin: 8px 0 0; max-width: 920px; color: #8b949e; line-height: 1.5; }}
        .stamp {{ display:inline-flex; margin-top: 14px; padding: 8px 12px; border-radius: 999px; border: 1px solid #30363d; color: #42a5f5; font-size: 12px; letter-spacing: 0.7px; text-transform: uppercase; }}
        .grid {{ display:grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 18px; }}
        .card {{ background: linear-gradient(180deg, rgba(22,27,34,0.96) 0%, rgba(13,17,23,0.98) 100%); border: 1px solid #30363d; border-radius: 18px; padding: 18px; box-shadow: 0 10px 28px rgba(0,0,0,0.22); }}
        .card-head {{ display:flex; justify-content:space-between; gap:16px; align-items:flex-start; margin-bottom: 8px; }}
        .kicker {{ font-size: 12px; letter-spacing: 1px; text-transform: uppercase; color: #8b949e; margin-bottom: 6px; }}
        .card h2 {{ margin:0; font-size: 22px; }}
        .card p {{ color: #e6edf3; line-height:1.5; margin: 8px 0 14px; }}
        .status {{ padding: 6px 10px; border:1px solid; border-radius:999px; font-size:12px; font-weight:700; letter-spacing:0.6px; }}
        .meta {{ display:grid; grid-template-columns: 110px 1fr; gap: 12px; padding: 8px 0; border-top: 1px solid rgba(255,255,255,0.06); }}
        .meta span {{ color:#8b949e; font-size:12px; text-transform:uppercase; letter-spacing:0.6px; }}
        .meta strong {{ font-size:13px; word-break:break-word; }}
        .runlog {{ margin-top: 14px; padding: 12px 14px; border-radius: 12px; background: rgba(255,255,255,0.03); color: #c9d1d9; font-size: 12px; line-height: 1.5; }}
        .actions {{ margin-top: 14px; }}
        .button {{ display:inline-flex; align-items:center; justify-content:center; padding: 10px 14px; border-radius: 10px; border: 1px solid #42a5f5; color: #42a5f5; text-decoration:none; font-weight:700; }}
        .button.disabled {{ border-color:#30363d; color:#8b949e; }}
        @media (max-width: 980px) {{ .grid {{ grid-template-columns: 1fr; }} }}
      </style>
    </head>
    <body>
      <div class="wrap">
        <div class="hero">
          <h1>QuantLab Dashboard Hub</h1>
          <p>Organized launcher for the live dashboards used in the Data Lab. This hub is auto-refreshed on workspace open so the newest Diet CTA and Quant dashboards are rebuilt without leaving duplicate versions lying around.</p>
          <div class="stamp">Last Hub Refresh: {timestamp}</div>
        </div>
        <div class="grid">{''.join(cards)}</div>
      </div>
    </body>
    </html>
    """
    OUTPUT_FILE.write_text(html, encoding="utf-8")


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    results = []
    for dashboard in DASHBOARDS[1:]:
        ok, message = run_dashboard(dashboard["script"], dashboard["output"])
        results.append({**dashboard, "ok": ok, "message": message})
    results.insert(0, {**DASHBOARDS[0], "ok": True, "message": "Central launcher generated from latest dashboard outputs."})
    render_hub(results)
    print(f"Dashboard hub updated: {datetime.now().strftime('%Y-%m-%d %I:%M %p')}")
    print(f"Hub saved to: {OUTPUT_FILE}")


if __name__ == "__main__":
    main()