"""
Markdown + JSON report renderer for query mode.

Produces the FORCED-ACTION MOMENTUM MAP report (two lenses).
"""
from __future__ import annotations

import json
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from .logger import get_logger

log = get_logger("query_report")

_ARB_TAG = "ARB LEVEL"
_WHO_ARB = "Non-options mechanical level; event/structure participants may defend/press around this price."
_BREACH_ARB = "If breached, structural participants may accelerate positioning around this price."
_REJ_ARB = "On rejection, structural participants may defend this price, especially near catalyst dates."


# ────────────────────────────────────────────────────────────
# MARKDOWN REPORT
# ────────────────────────────────────────────────────────────

def render_query_md(
    ticker: str,
    spot: float,
    asof_utc: str,
    session: str,
    lens_a: Dict[str, Any],
    lens_b: Dict[str, Any],
    monthly_proxy: bool,
    staleness_a: str,
    staleness_b: str,
    arb_levels: List[Dict[str, Any]],
    arb_lookback_days: int,
    paths_a: Dict[str, List[float]],
    paths_b: Dict[str, List[float]],
    verdict: Dict[str, str],
) -> str:
    """Build the full FORCED-ACTION MOMENTUM MAP markdown."""
    p: list[str] = []

    p.append(f"# FORCED-ACTION MOMENTUM MAP — {ticker}")
    p.append(f"### QUERY MODE — FRONT WEEK + CLOSEST MONTHLY")
    p.append("")

    # ── STEP 0 — VERIFY ──
    p.append("## STEP 0 — VERIFY")
    p.append(f"- **SPOT:** ${spot:,.2f}  (source: Alpaca snapshot)")
    p.append(f"- **AS-OF (UTC):** {asof_utc}")
    p.append(f"- **SESSION:** {session}")
    p.append("")

    # ── STEP 2 — STRIKES THAT MATTER ──
    p.append("## STEP 2 — STRIKES THAT MATTER (TWO LENSES)")
    p.append("")

    # LENS A
    exp_a = lens_a.get("expiration", "N/A")
    stale_a_tag = f"  [{staleness_a}]" if staleness_a else ""
    p.append(f"### LENS A: FRONT WEEK (EXP: {exp_a}){stale_a_tag}")
    _render_iv_line(p, lens_a)
    _render_levels_table(p, lens_a.get("levels", []))
    p.append("")

    # LENS B
    exp_b = lens_b.get("expiration", "N/A")
    proxy_tag = " [MONTHLY PROXY]" if monthly_proxy else ""
    stale_b_tag = f"  [{staleness_b}]" if staleness_b else ""
    p.append(f"### LENS B: CLOSEST MONTHLY (EXP: {exp_b}){proxy_tag}{stale_b_tag}")
    _render_iv_line(p, lens_b)
    _render_levels_table(p, lens_b.get("levels", []))
    p.append("")

    # ── STEP 3 — ARB / CONTRACTUAL ──
    p.append("## STEP 3 — ARB / CONTRACTUAL (MANDATORY)")
    if arb_levels:
        p.append("")
        p.append("| Level | Instrument Type | Filing Type | Filing Date | Source URL | Snippet |")
        p.append("|------:|:----------------|:------------|:------------|:-----------|:--------|")
        for a in arb_levels:
            level = a.get("level", 0)
            label = a.get("label", "")
            ftype = a.get("filing_type", "")
            fdate = a.get("filing_date", "")
            url = a.get("document_url") or a.get("filing_url") or ""
            snip = (a.get("context_snippet", "") or "")[:80].replace("|", "\\|")
            url_md = f"[link]({url})" if url else ""
            p.append(f"| ${level:,.2f} | {label} | {ftype} | {fdate} | {url_md} | {snip} |")
        p.append("")
    else:
        p.append(f"")
        p.append(f"NO CONTRACTUAL/ARB STRUCTURES VERIFIED — SOURCES CHECKED: SEC EDGAR (last {arb_lookback_days} days)")
        p.append("")

    # ── STEP 4 — DIRECTIONAL PATHS ──
    p.append("## STEP 4 — DIRECTIONAL PATHS (STRIKE-TO-STRIKE)")
    p.append("")
    _render_paths(p, "LENS A (FRONT WEEK)", paths_a, spot)
    _render_paths(p, "LENS B (CLOSEST MONTHLY)", paths_b, spot)

    # ── STEP 5 — VERDICT ──
    p.append("## STEP 5 — VERDICT")
    p.append(f"1. **REGIME:** {verdict.get('regime', 'UNVERIFIED')}")
    p.append(f"2. **PATH OF LEAST RESISTANCE:** {verdict.get('path_of_least_resistance', 'UNVERIFIED')}")
    p.append(f"3. **REGIME FLIP:** {verdict.get('regime_flip', 'N/A')}")
    p.append("")
    p.append("---")
    p.append("_Generated by Levels Engine (Query Mode) v0.1.0_")
    p.append("")

    return "\n".join(p)


def _render_iv_line(p: list[str], lens: Dict[str, Any]) -> None:
    atm = lens.get("iv_atm")
    med = lens.get("iv_near_median")
    atm_s = f"{atm * 100:.1f}%" if atm else "unavailable"
    med_s = f"{med * 100:.1f}%" if med else "unavailable"
    p.append(f"- **IV Snapshot:** ATM IV {atm_s} | Near-Spot Median IV {med_s}")
    p.append("")


def _render_levels_table(p: list[str], levels: List[Dict]) -> None:
    if not levels:
        p.append("_No levels available for this lens._")
        return
    p.append("| Strike | Type | OI | Volume | Who Is Forced | Breach | Rejection |")
    p.append("|-------:|:-----|---:|-------:|:--------------|:-------|:----------|")
    for lv in sorted(levels, key=lambda l: l["strike"]):
        strike = f"${lv['strike']:,.2f}"
        tag = lv.get("type", "")
        oi = f"{lv.get('oi', 0):,}"
        vol = f"{lv.get('volume', 0):,}"
        who = lv.get("who_is_forced", "")
        breach = lv.get("breach", "")
        rej = lv.get("rejection", "")
        p.append(f"| {strike} | {tag} | {oi} | {vol} | {who} | {breach} | {rej} |")


def _render_paths(p: list[str], label: str, paths: Dict, spot: float) -> None:
    p.append(f"**{label}:**")
    up = paths.get("upside", [])
    down = paths.get("downside", [])
    if up:
        chain = " → ".join([f"${spot:,.2f}"] + [f"${s:,.2f}" for s in up[:5]])
        p.append(f"- UPSIDE PATH: {chain}")
    else:
        p.append("- UPSIDE PATH: no call concentrations above spot")
    if down:
        chain = " → ".join([f"${spot:,.2f}"] + [f"${s:,.2f}" for s in down[:5]])
        p.append(f"- DOWNSIDE PATH: {chain}")
    else:
        p.append("- DOWNSIDE PATH: no put concentrations below spot")
    p.append("")


# ────────────────────────────────────────────────────────────
# JSON OUTPUT
# ────────────────────────────────────────────────────────────

def build_query_json(
    ticker: str,
    spot: float,
    asof_utc: str,
    session: str,
    lens_a: Dict[str, Any],
    lens_b: Dict[str, Any],
    monthly_proxy: bool,
    staleness_a: str,
    staleness_b: str,
    arb_levels: List[Dict[str, Any]],
    paths_a: Dict[str, List[float]],
    paths_b: Dict[str, List[float]],
    verdict: Dict[str, str],
    diagnostics: Dict[str, Any],
) -> Dict[str, Any]:
    return {
        "ticker": ticker,
        "spot": spot,
        "asof_utc": asof_utc,
        "session": session,
        "lens_front_week": {
            "expiry": lens_a.get("expiration"),
            "staleness_label": staleness_a,
            "iv_atm": lens_a.get("iv_atm"),
            "iv_near_median": lens_a.get("iv_near_median"),
            "levels": lens_a.get("levels", []),
        },
        "lens_monthly": {
            "expiry": lens_b.get("expiration"),
            "monthly_proxy_flag": monthly_proxy,
            "staleness_label": staleness_b,
            "iv_atm": lens_b.get("iv_atm"),
            "iv_near_median": lens_b.get("iv_near_median"),
            "levels": lens_b.get("levels", []),
        },
        "arb_levels_verified": arb_levels,
        "paths_front_week": paths_a,
        "paths_monthly": paths_b,
        "verdict": verdict,
        "diagnostics": diagnostics,
    }
