#!/usr/bin/env python3
"""
Studies Router -- Natural-language query -> study dispatch.

Loads studies_registry.yaml, scores each study by keyword matches
against the user query, and runs the best-matching study's run_study.py.

Can also accept a pre-built --spec YAML (generated by ask.py).

Usage:
    python tools/studies/route_study.py "trend vs chop in uptrend for NVDA" --tickers NVDA TSLA --start 2018-01-01 --end 2026-02-15 --intraday false
    python tools/studies/route_study.py --spec path/to/run_spec.yaml
    python tools/studies/route_study.py "gap up close strong by bin"
"""
from __future__ import annotations

import argparse
import subprocess
import sys
import yaml
from pathlib import Path

TOOLS_DIR = Path(__file__).resolve().parent          # tools/studies/
ROOT_DIR = TOOLS_DIR.parent.parent                   # Data_Lab root
REGISTRY_PATH = TOOLS_DIR / "studies_registry.yaml"


def load_registry() -> dict:
    """Load the studies registry YAML."""
    if not REGISTRY_PATH.exists():
        print(f"ERROR: Registry not found at {REGISTRY_PATH}", file=sys.stderr)
        sys.exit(1)
    with open(REGISTRY_PATH, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def score_query(query: str, keywords: list[str]) -> int:
    """Count how many keywords appear in the query (case-insensitive)."""
    q = query.lower()
    return sum(1 for kw in keywords if kw.lower() in q)


def match_study(query: str, registry: dict) -> tuple[str, dict]:
    """
    Find the best-matching study for a query.
    Ties broken by most keyword matches, then alphabetical study name.
    Returns (study_name, study_config).
    """
    studies = registry.get("studies", {})
    if not studies:
        print("ERROR: No studies registered.", file=sys.stderr)
        sys.exit(1)

    scored: list[tuple[int, str, dict]] = []
    for name, cfg in studies.items():
        keywords = cfg.get("keywords", [])
        s = score_query(query, keywords)
        scored.append((s, name, cfg))

    # Sort by score descending, then name ascending for deterministic tie-break
    scored.sort(key=lambda x: (-x[0], x[1]))

    best_score, best_name, best_cfg = scored[0]
    if best_score == 0:
        print(f"WARNING: No keyword matches for query: \"{query}\"")
        print("Available studies and their keywords:")
        for _, name, cfg in scored:
            kws = ", ".join(cfg.get("keywords", []))
            print(f"  {name}: {kws}")
        print(f"\nDefaulting to first study alphabetically: {best_name}")

    return best_name, best_cfg


def run_study_with_args(study_name: str, study_cfg: dict,
                        args: argparse.Namespace) -> None:
    """Execute the matched study's run_study.py with CLI args (legacy mode)."""
    entrypoint = study_cfg.get("entrypoint", "")
    study_script = ROOT_DIR / entrypoint
    if not study_script.exists():
        print(f"ERROR: Entrypoint not found: {study_script}", file=sys.stderr)
        sys.exit(1)

    study_dir = study_script.parent

    cmd = [sys.executable, str(study_script)]
    if args.tickers:
        cmd.extend(["--tickers"] + args.tickers)
    if args.start:
        cmd.extend(["--start", args.start])
    if args.end:
        cmd.extend(["--end", args.end])
    if args.intraday is not None:
        cmd.extend(["--intraday", args.intraday])

    _run_and_print(study_name, study_cfg, cmd, study_dir)


def run_study_with_spec(spec_path: str) -> None:
    """Execute a study using a pre-built run_spec.yaml."""
    spec_file = Path(spec_path)
    if not spec_file.exists():
        print(f"ERROR: Spec file not found: {spec_file}", file=sys.stderr)
        sys.exit(1)

    with open(spec_file, "r", encoding="utf-8") as f:
        spec = yaml.safe_load(f)

    study_name = spec.get("study", "")
    registry = load_registry()
    studies = registry.get("studies", {})
    study_cfg = studies.get(study_name, {})

    entrypoint = study_cfg.get("entrypoint", "")
    if not entrypoint:
        entrypoint = f"studies/{study_name}/run_study.py"
    study_script = ROOT_DIR / entrypoint
    if not study_script.exists():
        print(f"ERROR: Entrypoint not found: {study_script}", file=sys.stderr)
        sys.exit(1)

    study_dir = study_script.parent
    cmd = [sys.executable, str(study_script), "--spec", str(spec_file.resolve())]

    _run_and_print(study_name, study_cfg, cmd, study_dir)


def _run_and_print(study_name: str, study_cfg: dict,
                   cmd: list[str], study_dir: Path) -> None:
    print(f"{'='*60}")
    print(f"STUDY MATCHED: {study_name}")
    print(f"Description:   {study_cfg.get('description', 'N/A')}")
    print(f"Command:       {' '.join(cmd)}")
    print(f"Working dir:   {study_dir}")
    print(f"{'='*60}\n")

    result = subprocess.run(cmd, cwd=str(study_dir))

    print(f"\n{'='*60}")
    print(f"STUDY COMPLETE: {study_name}")
    print(f"Exit code:     {result.returncode}")
    print(f"Outputs:       {study_dir / 'outputs'}")
    print(f"{'='*60}")

    if result.returncode != 0:
        sys.exit(result.returncode)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Route a natural-language query to the matching study."
    )
    parser.add_argument("query", nargs="?", default=None,
                        help="Natural language query")
    parser.add_argument("--spec", default=None,
                        help="Path to a pre-built run_spec.yaml")
    parser.add_argument("--tickers", nargs="*", default=None,
                        help="Ticker symbols (e.g., NVDA TSLA)")
    parser.add_argument("--start", default=None,
                        help="Start date YYYY-MM-DD")
    parser.add_argument("--end", default=None,
                        help="End date YYYY-MM-DD")
    parser.add_argument("--intraday", default=None,
                        help="Enable intraday analysis (true/false)")
    args = parser.parse_args()

    if args.spec:
        run_study_with_spec(args.spec)
    elif args.query:
        registry = load_registry()
        study_name, study_cfg = match_study(args.query, registry)
        run_study_with_args(study_name, study_cfg, args)
    else:
        parser.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
