"""
War Room Earnings Prefetch — Data Bridge
=========================================
Pulls fundamental data from FMP for a ticker and writes a structured
markdown file to data/prefetch/ for consumption by Claude Code during
War Room analysis.

EARNINGS ONLY. Do not use for non-earnings catalysts.

Usage:
    python scripts/war_room_prefetch.py --ticker NVDA
    python scripts/war_room_prefetch.py --ticker NVDA --quarters 8
"""

import sys
import argparse
from pathlib import Path
from datetime import date

# ── Path setup (non-negotiable) ──────────────────────────────────
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "shared"))
sys.path.insert(0, str(ROOT / "shared" / "config"))
sys.path.insert(0, str(ROOT / "tools"))

from shared.config.api_clients import FMPClient

PREFETCH_DIR = ROOT / "My Data" / "prefetch"
PREFETCH_DIR.mkdir(parents=True, exist_ok=True)


def safe_call(func, *args, label="", **kwargs):
    """Call an API method, return result or None on failure."""
    try:
        result = func(*args, **kwargs)
        if isinstance(result, dict) and "Error Message" in result:
            print(f"  ⚠️  {label}: API error — {result['Error Message']}")
            return None
        return result
    except Exception as e:
        print(f"  ⚠️  {label}: {e}")
        return None


def fmt(val, suffix="", fallback="N/A"):
    """Format a value for display. Returns fallback if None."""
    if val is None:
        return fallback
    if isinstance(val, float):
        if suffix == "%":
            return f"{val:.2f}%"
        if suffix == "x":
            return f"{val:.2f}x"
        if abs(val) >= 1_000_000_000:
            return f"${val / 1_000_000_000:.2f}B"
        if abs(val) >= 1_000_000:
            return f"${val / 1_000_000:.1f}M"
        return f"{val:.2f}{suffix}"
    return f"{val}{suffix}"


def pct(val, fallback="N/A"):
    """Format as percentage."""
    if val is None:
        return fallback
    return f"{val * 100:.2f}%" if abs(val) < 1 else f"{val:.2f}%"


def calc_yoy(current, year_ago):
    """Calculate YoY growth %."""
    if current is None or year_ago is None or year_ago == 0:
        return None
    return ((current - year_ago) / abs(year_ago)) * 100


def calc_qoq(current, prior):
    """Calculate sequential growth %."""
    if current is None or prior is None or prior == 0:
        return None
    return ((current - prior) / abs(prior)) * 100


def margin_trend_tag(values):
    """Given a list of margin values (newest first), return a trend tag."""
    clean = [v for v in values if v is not None]
    if len(clean) < 2:
        return "INSUFFICIENT DATA"
    # Compare newest vs oldest
    delta = clean[0] - clean[-1]
    recent_delta = clean[0] - clean[1] if len(clean) >= 2 else 0
    if delta > 2 and recent_delta > 0:
        return "ACCELERATING ↑"
    elif delta > 0.5:
        return "EXPANDING ↑"
    elif delta > -0.5:
        return "STABLE →"
    elif delta > -2:
        return "COMPRESSING ↓"
    else:
        return "DETERIORATING ↓↓"


def build_prefetch(ticker: str, num_quarters: int = 5):
    """Pull all data and build the prefetch markdown file."""
    ticker = ticker.upper().strip()
    today = date.today().strftime("%Y-%m-%d")
    filename = f"{ticker}_{date.today().strftime('%Y%m%d')}.md"
    outpath = PREFETCH_DIR / filename

    fmp = FMPClient()
    lines = []

    def section(title):
        lines.append(f"\n## {title}\n")

    def line(text):
        lines.append(text)

    lines.append(f"# PREFETCH: {ticker} | {today} | EARNINGS ANALYSIS DATA")
    lines.append(f"# Generated by war_room_prefetch.py — for War Room v10.0 consumption")
    lines.append(f"# This file is EARNINGS DATA ONLY. News/transcripts come from web search.")
    lines.append("")

    # ── 1. COMPANY SNAPSHOT ──────────────────────────────────────
    print(f"  Pulling company profile...")
    profile_raw = safe_call(fmp.get_company_profile, ticker, label="Profile")
    profile = profile_raw[0] if profile_raw and isinstance(profile_raw, list) and len(profile_raw) > 0 else {}

    quote_raw = safe_call(fmp.get_quote, ticker, label="Quote")
    quote = quote_raw[0] if quote_raw and isinstance(quote_raw, list) and len(quote_raw) > 0 else {}

    section("COMPANY SNAPSHOT")
    line(f"- **Ticker:** {ticker}")
    line(f"- **Company:** {profile.get('companyName', 'N/A')}")
    line(f"- **Sector:** {profile.get('sector', 'N/A')} | **Industry:** {profile.get('industry', 'N/A')}")
    line(f"- **Market Cap:** {fmt(profile.get('mktCap'), fallback='N/A')}")
    line(f"- **Price:** ${quote.get('price', 'N/A')} | **Change:** {quote.get('changesPercentage', 'N/A')}%")
    line(f"- **52w Range:** ${quote.get('yearLow', '?')} — ${quote.get('yearHigh', '?')}")
    line(f"- **Avg Volume:** {fmt(quote.get('avgVolume'), fallback='N/A')}")
    line(f"- **Exchange:** {profile.get('exchangeShortName', 'N/A')}")
    line(f"- **IPO Date:** {profile.get('ipoDate', 'N/A')}")
    line(f"- **Description:** {profile.get('description', 'N/A')[:200]}...")

    # ── 2. FLOAT & SHORT INTEREST ────────────────────────────────
    print(f"  Pulling float data...")
    float_raw = safe_call(fmp.get_shares_float, ticker, label="Float")
    float_data = float_raw[0] if float_raw and isinstance(float_raw, list) and len(float_raw) > 0 else {}

    section("FLOAT & SHORT INTEREST")
    line(f"- **Shares Outstanding:** {fmt(float_data.get('outstandingShares'), fallback='N/A')}")
    line(f"- **Free Float:** {fmt(float_data.get('freeFloat'), fallback='N/A')}")
    line(f"- **Float %:** {fmt(float_data.get('floatShares'), fallback='N/A')}")

    # ── 3. RECENT QUARTERS ───────────────────────────────────────
    print(f"  Pulling income statements ({num_quarters}Q)...")
    income = safe_call(fmp.get_income_statement, ticker, period='quarter', label="Income Statement")
    if income and isinstance(income, list):
        income = income[:num_quarters]
    else:
        income = []

    print(f"  Pulling balance sheets ({num_quarters}Q)...")
    balance = safe_call(fmp.get_balance_sheet, ticker, period='quarter', label="Balance Sheet")
    if balance and isinstance(balance, list):
        balance = balance[:num_quarters]
    else:
        balance = []

    print(f"  Pulling cash flow ({num_quarters}Q)...")
    cashflow = safe_call(fmp.get_cash_flow, ticker, period='quarter', label="Cash Flow")
    if cashflow and isinstance(cashflow, list):
        cashflow = cashflow[:num_quarters]
    else:
        cashflow = []

    section(f"RECENT QUARTERS ({len(income)}Q)")

    if income:
        # Table header
        line("| Quarter | Revenue | YoY Rev | QoQ Rev | Gross Margin | Op Margin | Net Margin | EPS |")
        line("|---------|---------|---------|---------|-------------|-----------|------------|-----|")

        gm_values = []
        om_values = []
        fcf_values = []

        for i, q in enumerate(income):
            rev = q.get('revenue')
            gp = q.get('grossProfit')
            oi = q.get('operatingIncome')
            ni = q.get('netIncome')
            eps = q.get('eps') or q.get('epsdiluted')
            period_label = q.get('period', '?')
            cal_year = q.get('calendarYear', '?')
            label = f"{period_label} {cal_year}"

            gm = (gp / rev * 100) if rev and gp else None
            om = (oi / rev * 100) if rev and oi else None
            nm = (ni / rev * 100) if rev and ni else None

            gm_values.append(gm)
            om_values.append(om)

            # YoY: compare to same quarter last year (index i+4 if available)
            yoy_rev = None
            if i + 4 < len(income) and income[i + 4].get('revenue'):
                yoy_rev = calc_yoy(rev, income[i + 4].get('revenue'))

            # QoQ: compare to prior quarter (index i+1)
            qoq_rev = None
            if i + 1 < len(income) and income[i + 1].get('revenue'):
                qoq_rev = calc_qoq(rev, income[i + 1].get('revenue'))

            line(f"| {label} | {fmt(rev)} | {fmt(yoy_rev, '%') if yoy_rev is not None else 'N/A'} | "
                 f"{fmt(qoq_rev, '%') if qoq_rev is not None else 'N/A'} | "
                 f"{fmt(gm, '%')} | {fmt(om, '%')} | {fmt(nm, '%')} | "
                 f"${eps if eps else 'N/A'} |")

        # FCF from cash flow
        for cq in cashflow:
            ocf = cq.get('operatingCashFlow')
            capex = cq.get('capitalExpenditure')
            fcf = (ocf + capex) if ocf is not None and capex is not None else None  # capex is negative
            fcf_values.append(fcf)
    else:
        line("⚠️ Income statement data unavailable")

    # ── 4. MARGIN TRAJECTORY ─────────────────────────────────────
    section("MARGIN TRAJECTORY")

    if income and len(income) >= 2:
        line(f"- **Gross Margin trend:** {' → '.join([fmt(v, '%') for v in gm_values if v is not None])} **[{margin_trend_tag(gm_values)}]**")
        line(f"- **Op Margin trend:** {' → '.join([fmt(v, '%') for v in om_values if v is not None])} **[{margin_trend_tag(om_values)}]**")

        if fcf_values:
            line(f"- **FCF trend:** {' → '.join([fmt(v) for v in fcf_values if v is not None])}")
    else:
        line("⚠️ Insufficient data for margin trajectory")

    # ── 5. OPERATING LEVERAGE SIGNALS (§11B) ─────────────────────
    section("OP LEVERAGE SIGNALS (WAR ROOM §11B)")

    if income and len(income) >= 2:
        q0, q1 = income[0], income[1]
        rev0, rev1 = q0.get('revenue'), q1.get('revenue')
        gp0, gp1 = q0.get('grossProfit'), q1.get('grossProfit')
        oi0, oi1 = q0.get('operatingIncome'), q1.get('operatingIncome')
        sga0, sga1 = q0.get('sellingGeneralAndAdministrativeExpenses'), q1.get('sellingGeneralAndAdministrativeExpenses')

        gm0 = (gp0 / rev0 * 100) if rev0 and gp0 else None
        gm1 = (gp1 / rev1 * 100) if rev1 and gp1 else None
        om0 = (oi0 / rev0 * 100) if rev0 and oi0 else None
        om1 = (oi1 / rev1 * 100) if rev1 and oi1 else None

        # Signal A: Op Leverage Delta
        if gm0 is not None and gm1 is not None and om0 is not None and om1 is not None:
            gm_delta = gm0 - gm1
            om_delta = om0 - om1
            op_lev = om_delta - gm_delta
            verdict_a = "✅ POSITIVE — fixed costs being absorbed" if op_lev > 0 else "❌ NEGATIVE — cost growth outpacing"
            line(f"- **Signal A — Op Leverage Delta:** {fmt(op_lev, ' bps')} → {verdict_a}")
        else:
            line("- **Signal A — Op Leverage Delta:** N/A")

        # Signal B: Incremental Margin
        if rev0 is not None and rev1 is not None and oi0 is not None and oi1 is not None:
            rev_change = rev0 - rev1
            oi_change = oi0 - oi1
            if rev_change != 0:
                incr_margin = (oi_change / rev_change) * 100
                current_om = om0 if om0 else 0
                verdict_b = "✅ COMPOUNDER" if incr_margin > current_om else "⚠️ HIDDEN PEAK — incremental < current"
                line(f"- **Signal B — Incremental Margin:** {fmt(incr_margin, '%')} vs current OM {fmt(current_om, '%')} → {verdict_b}")
            else:
                line("- **Signal B — Incremental Margin:** N/A (flat revenue)")
        else:
            line("- **Signal B — Incremental Margin:** N/A")

        # Signal C: SG&A Leverage
        if sga0 is not None and sga1 is not None and rev0 and rev1:
            sga_pct0 = sga0 / rev0 * 100
            sga_pct1 = sga1 / rev1 * 100
            sga_delta = sga_pct0 - sga_pct1
            verdict_c = "✅ SCALING — SG&A% declining" if sga_delta < 0 else "⚠️ SG&A% rising"
            line(f"- **Signal C — SG&A Leverage:** {fmt(sga_pct0, '%')} vs prior {fmt(sga_pct1, '%')} ({fmt(sga_delta, ' bps')}) → {verdict_c}")
        else:
            line("- **Signal C — SG&A Leverage:** N/A")

        # Signal D: FCF Conversion
        if cashflow and len(cashflow) >= 1:
            cq0 = cashflow[0]
            ocf = cq0.get('operatingCashFlow')
            ebitda = q0.get('ebitda') or q0.get('ebitdaratio')
            # Try to compute EBITDA from income
            if ebitda is None:
                da = q0.get('depreciationAndAmortization', 0) or 0
                if oi0:
                    ebitda = oi0 + da
            if ocf is not None and ebitda and ebitda != 0:
                fcf_conv = (ocf / ebitda) * 100
                verdict_d = "✅ HEALTHY" if fcf_conv > 80 else "⚠️ BELOW 80% — check working capital"
                line(f"- **Signal D — FCF Conversion:** {fmt(fcf_conv, '%')} (OCF/EBITDA) → {verdict_d}")
            else:
                line("- **Signal D — FCF Conversion:** N/A")
        else:
            line("- **Signal D — FCF Conversion:** N/A")

        # Double Compounder Tag
        signals_positive = sum(1 for l in lines[-4:] if "✅" in l)
        if signals_positive == 4:
            line("\n**🏆 DOUBLE COMPOUNDER: TRUE — All 4 signals positive**")
        elif signals_positive == 3:
            line(f"\n**📈 STRONG COMPOUNDER: 3/4 signals positive**")
        elif signals_positive == 2:
            line(f"\n**📊 DEVELOPING: 2/4 signals positive**")
        else:
            line(f"\n**⚠️ NOT A COMPOUNDER: {signals_positive}/4 signals positive**")
    else:
        line("⚠️ Insufficient quarterly data for op leverage analysis")

    # ── 6. FORWARD ESTIMATES ─────────────────────────────────────
    print(f"  Pulling analyst estimates...")
    estimates = safe_call(fmp.get_analyst_estimates, ticker, period='quarter', limit=4, label="Estimates")

    section("FORWARD ESTIMATES (CONSENSUS)")

    if estimates and isinstance(estimates, list) and len(estimates) > 0:
        line("| Quarter | Est. Revenue | Est. EPS | Est. EBITDA |")
        line("|---------|-------------|---------|-------------|")
        for est in estimates[:4]:
            dt = est.get('date', '?')
            line(f"| {dt} | {fmt(est.get('estimatedRevenueAvg'))} | "
                 f"${est.get('estimatedEpsAvg', 'N/A')} | "
                 f"{fmt(est.get('estimatedEbitdaAvg'))} |")
    else:
        line("⚠️ Analyst estimates unavailable")

    # ── 7. ANALYST CONSENSUS ─────────────────────────────────────
    print(f"  Pulling analyst consensus...")
    pt = safe_call(fmp.get_price_target_consensus, ticker, label="PT Consensus")
    grades = safe_call(fmp.get_grades_consensus, ticker, limit=10, label="Grades")

    section("ANALYST CONSENSUS")

    if pt and isinstance(pt, list) and len(pt) > 0:
        ptd = pt[0]
        line(f"- **Target Price Consensus:** Mean ${ptd.get('targetConsensus', 'N/A')} | "
             f"High ${ptd.get('targetHigh', 'N/A')} | Low ${ptd.get('targetLow', 'N/A')}")
    elif pt and isinstance(pt, dict):
        line(f"- **Target Price Consensus:** Mean ${pt.get('targetConsensus', 'N/A')} | "
             f"High ${pt.get('targetHigh', 'N/A')} | Low ${pt.get('targetLow', 'N/A')}")
    else:
        line("- **Target Price Consensus:** ⚠️ unavailable")

    if grades and isinstance(grades, list) and len(grades) > 0:
        line("\n**Recent Analyst Actions:**")
        line("| Date | Firm | Action | From → To |")
        line("|------|------|--------|-----------|")
        for g in grades[:8]:
            line(f"| {g.get('date', '?')} | {g.get('gradingCompany', '?')} | "
                 f"{g.get('newGrade', '?')} | {g.get('previousGrade', '?')} → {g.get('newGrade', '?')} |")
    else:
        line("\n**Recent Analyst Actions:** ⚠️ unavailable")

    # ── 8. VALUATION SNAPSHOT ────────────────────────────────────
    print(f"  Pulling valuation metrics...")
    ratios_ttm = safe_call(fmp.get_ratios_ttm, ticker, label="Ratios TTM")
    key_metrics = safe_call(fmp.get_key_metrics, ticker, period='quarter', limit=1, label="Key Metrics")

    section("VALUATION SNAPSHOT")

    if ratios_ttm and isinstance(ratios_ttm, list) and len(ratios_ttm) > 0:
        r = ratios_ttm[0]
        line(f"- **P/E (TTM):** {fmt(r.get('peRatioTTM'), 'x')}")
        line(f"- **P/S (TTM):** {fmt(r.get('priceToSalesRatioTTM'), 'x')}")
        line(f"- **P/B (TTM):** {fmt(r.get('priceToBookRatioTTM'), 'x')}")
        line(f"- **EV/EBITDA (TTM):** {fmt(r.get('enterpriseValueOverEBITDATTM'), 'x')}")
        line(f"- **EV/Revenue (TTM):** {fmt(r.get('priceToSalesRatioTTM'), 'x')}")
        line(f"- **FCF Yield (TTM):** {fmt(r.get('freeCashFlowYieldTTM'), '%')}")
        line(f"- **Dividend Yield (TTM):** {fmt(r.get('dividendYieldTTM'), '%')}")
        line(f"- **ROE (TTM):** {fmt(r.get('returnOnEquityTTM'), '%')}")
        line(f"- **ROIC (TTM):** {fmt(r.get('returnOnCapitalEmployedTTM'), '%')}")
    else:
        line("⚠️ TTM ratios unavailable")

    if key_metrics and isinstance(key_metrics, list) and len(key_metrics) > 0:
        km = key_metrics[0]
        line(f"- **Enterprise Value:** {fmt(km.get('enterpriseValue'))}")
        line(f"- **Revenue Per Share:** ${km.get('revenuePerShare', 'N/A')}")
        line(f"- **Net Debt:** {fmt(km.get('netDebtPerShare'), fallback='N/A')}/share")

    # ── 9. EARNINGS SURPRISE HISTORY ─────────────────────────────
    print(f"  Pulling earnings surprises...")
    surprises = safe_call(fmp.get_earnings_surprises, ticker, label="Earnings Surprises")

    section("EARNINGS SURPRISE HISTORY (Last 4Q)")

    if surprises and isinstance(surprises, list) and len(surprises) > 0:
        line("| Date | Actual EPS | Estimated EPS | Surprise |")
        line("|------|-----------|--------------|----------|")
        for s in surprises[:4]:
            actual = s.get('actualEarningResult')
            est = s.get('estimatedEarning')
            surprise_val = None
            if actual is not None and est is not None and est != 0:
                surprise_val = ((actual - est) / abs(est)) * 100
            line(f"| {s.get('date', '?')} | ${actual if actual is not None else 'N/A'} | "
                 f"${est if est is not None else 'N/A'} | "
                 f"{fmt(surprise_val, '%') if surprise_val is not None else 'N/A'} |")
    else:
        line("⚠️ Earnings surprise data unavailable")

    # ── FOOTER ───────────────────────────────────────────────────
    lines.append("\n---")
    lines.append(f"*Prefetch generated {today}. Data source: FMP (Financial Modeling Prep).*")
    lines.append("*This file covers NUMBERS ONLY. News, transcripts, sentiment, and narrative")
    lines.append("context must come from web search during War Room analysis.*")

    # ── Write file ───────────────────────────────────────────────
    outpath.write_text("\n".join(lines), encoding="utf-8")
    print(f"\n✅ Prefetch saved: {outpath.relative_to(ROOT)}")
    return outpath


def main():
    parser = argparse.ArgumentParser(description="War Room Earnings Prefetch")
    parser.add_argument("--ticker", "-t", required=True, help="Stock ticker (e.g., NVDA)")
    parser.add_argument("--quarters", "-q", type=int, default=5,
                        help="Number of trailing quarters to pull (default: 5)")
    args = parser.parse_args()

    print(f"🔄 Prefetching earnings data for {args.ticker.upper()}...")
    build_prefetch(args.ticker, num_quarters=args.quarters)


if __name__ == "__main__":
    main()
